[package]
name = "tests"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
analyzer = { path = "../analyzer" }
shared_ast = { path = "../shared_ast" }
prost = "0.11"
which = "4"

[[test]]
name = "symbol_table"
path = "symbol_table_tests.rs"

[[test]]
name = "semantic_analysis"
path = "semantic_analysis_tests.rs"

[[test]]
name = "borrow_check"
path = "borrow_check_tests.rs"

[[test]]
name = "backend_integration"
path = "backend_integration_test.rs"

[[test]]
name = "print_read"
path = "print_read_test.rs"

[[test]]
name = "backend_lowering"
path = "backend_lowering_tests.rs"

[[test]]
name = "linking"
path = "linking_test.rs"

[[test]]
name = "boundary"
path = "boundary_tests.rs"
